default: &default
  adapter: postgresql
  encoding: unicode
  pool: <%= ENV.fetch("RAILS_MAX_THREADS") { 5 } %>

development:
  <<: *default
  database: EmployeeDir_development

test:
  <<: *default
  database: EmployeeDir_test

production:
  <<: *default
  database: EmployeeDir_production
  username: EmployeeDir
  password: <%= ENV['EMPLOYEEDIR_DATABASE_PASSWORD'] %>
